export const niches = [
  'Artes',
  'Artigos de Luxo',
  'Ativismo & Causas Sociais',
  'Beleza & Maquiagem',
  'Brinquedos',
  'Carros, Motocicletas & Veiculos',
  'Casamento',
  'Ciências & Curiosidades',
  'Churrasco',
  'Construção Civil',
  'Crianças & Bebês',
  'Cultura Nerd',
  'Decoração',
  'Diversidade & Empoderamento',
  'Educação',
  'Esportes',
  'Faça Você Mesmo',
  'Família & Maternidade',
  'Fitness',
  'Finanças',
  'Games',
  'Gastronomia, Comidas, Bebidas & Receitas',
  'Humor',
  'Lifestyle',
  'Livros & Leitura',
  'Moda',
  'Música',
  'Negócios & Empreendedorismo',
  'Opinião',
  'Pets, Animais, Biologia',
  'Saúde',
  'Tecnologia',
  'Varejo',
  'Variedades',
  'Viagens',
  'Política',
  'Tv, Séries, Filmes, Cinema',
  'Direito, Advocacia',
  'Fotografia',
  'Agricultura, Rural',
  'Dança',
  'Notícias & Atualidades',
];
